teams = {"Alabama": 1,
         "Texas A&M-CC": 16,
         "Maryland": 8,
         "West Virginia": 9,
         "San Diego St": 5,
         "Charleston": 12,
         "Virginia": 4,
         "Furman": 13,
         "Creighton": 6,
         "NC State": 11,
         "Baylor": 3,
         "UCSB": 14,
         "Missouri": 7,
         "Utah State": 10,
         "Arizona": 2,
         "Princeton": 15,
         "Purdue": 1,
         "Farleigh Dickinson": 16,
         "Memphis": 8,
         "FAU": 9,
         "Duke": 5,
         "Oral Roberts": 12,
         "Tennessee": 4,
         "Louisiana": 13,
         "Kentucky": 6,
         "Providence": 11,
         "Kansas St": 3,
         "Montana St": 14,
         "Michigan St": 7,
         "USC": 10,
         "Marquette": 2,
         "Vermont": 15,
         "Houston": 1,
         "N Kentucky": 16,
         "Iowa": 8,
         "Auburn": 9,
         "Miami": 5,
         "Drake": 12,
         "Indiana": 4,
         "Kent State": 60,
         "Iowa State": 6,
         "Pittsburgh": 11,
         "Xavier": 3,
         "Kennesaw St": 14,
         "Texas A&M": 7,
         "Penn State": 10,
         "Texas": 2,
         "Colgate": 15,
         "Kansas": 1,
         "Howard": 16,
         "Arkansas": 8,
         "Illinois": 9,
         "Saint Mary's": 5,
         "VCU": 12,
         "UConn": 4,
         "Iona": 13,
         "TCU": 6,
         "Arizona State": 11,
         "Gonzaga": 3,
         "Grand Canyon": 14,
         "Northwestern": 7,
         "Boise St": 10,
         "UCLA": 2,
         "UNC Asheville": 15}

teams_32 = ["Alabama",
            "Maryland",
            "San Diego St",
            "Furman",
            "Creighton",
            "Baylor",
            "Missouri",
            "Princeton",
            "Farleigh Dickinson",
            "FAU",
            "Duke",
            "Tennessee",
            "Kentucky",
            "Kansas St",
            "Michigan St",
            "Marquette",
            "Houston",
            "Auburn",
            "Miami",
            "Indiana",
            "Pittsburgh",
            "Xavier",
            "Penn State",
            "Texas",
            "Kansas",
            "Arkansas",
            "Saint Mary's",
            "UConn",
            "TCU",
            "Gonzaga",
            "Northwestern",
            "UCLA"]

teams_16 = ["Alabama",
            "San Diego St",
            "Creighton",
            "Princeton",
            "FAU",
            "Tennessee",
            "Kansas St",
            "Michigan St",
            "Houston",
            "Miami",
            "Xavier",
            "Texas",
            "Arkansas",
            "UConn",
            "Gonzaga",
            "UCLA"]

def score(teams, seeds=None):
    total = 0
    if type(teams) is dict:
        for key in teams:
            total += teams[key]
    elif type(teams) is list:
        if seeds == None:
            print("A seeding dictionary must be input along with the list of teams.")
            return None
        for name in teams:
            total += seeds[name]
    else:
        print("TypeError: Input must be a dictionary or list. If a list, a seeding dictionary must also be input.")
        return None
    return total